# Generated by Django 3.1.7 on 2021-06-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_unmanned_ticket',
            field=models.BooleanField(default=True),
        ),
    ]
