# Generated by Django 3.1.7 on 2021-06-16 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_auto_20210608_1807'),
        ('users', '0002_user_is_unmanned_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTheater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='theaters.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_theaters',
                'unique_together': {('theater', 'user')},
            },
        ),
    ]
