# Generated by Django 3.1.7 on 2021-06-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favoritetheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_settings',
            field=models.JSONField(default=dict),
        ),
    ]
