# Generated by Django 3.1.7 on 2021-06-04 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('theater_screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theaterscreen')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
            options={
                'db_table': 'ticket_types',
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.tickettype')),
            ],
            options={
                'db_table': 'reservation_items',
            },
        ),
    ]
