# Generated by Django 3.1.7 on 2021-06-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('name', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'screens',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.city')),
            ],
            options={
                'db_table': 'theaters',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
            options={
                'db_table': 'ticket_types',
            },
        ),
        migrations.CreateModel(
            name='TheaterScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('is_screened', models.BooleanField()),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.screen')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.theater')),
            ],
            options={
                'db_table': 'theater_screens',
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservations')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.tickettype')),
            ],
            options={
                'db_table': 'reservation_items',
            },
        ),
        migrations.AddField(
            model_name='reservations',
            name='theater_screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.theaterscreen'),
        ),
    ]
