# Generated by Django 3.1.7 on 2021-03-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210304_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.tag'),
        ),
    ]
