# Generated by Django 3.1.7 on 2021-06-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tag',
        ),
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.ManyToManyField(to='movie.Tag'),
        ),
    ]
