# Generated by Django 3.1.7 on 2021-06-01 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movies',
            name='actor',
            field=models.ManyToManyField(to='movies.Actor'),
        ),
        migrations.AddField(
            model_name='movies',
            name='audience_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.audiencerating'),
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.ManyToManyField(to='movies.Director'),
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='movies',
            name='tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.tag'),
        ),
        migrations.AddField(
            model_name='movies',
            name='type',
            field=models.ManyToManyField(to='movies.Type'),
        ),
        migrations.AddField(
            model_name='like',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='movies.movies'),
        ),
        migrations.AddField(
            model_name='like',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.movies'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('movies', 'users')},
        ),
    ]
