# Generated by Django 3.1.7 on 2021-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210601_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
